// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mensagem.proto

package ifpb;

public final class MensagemOuterClass {
  private MensagemOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Mensagem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Mensagem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Resultado_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Resultado_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016mensagem.proto\"$\n\010Mensagem\022\n\n\002id\030\001 \001(\t" +
      "\022\014\n\004text\030\002 \001(\t\"%\n\tResultado\022\n\n\002id\030\001 \001(\t\022" +
      "\014\n\004hash\030\002 \001(\tB\010\n\004ifpbP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Mensagem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Mensagem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Mensagem_descriptor,
        new java.lang.String[] { "Id", "Text", });
    internal_static_Resultado_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Resultado_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Resultado_descriptor,
        new java.lang.String[] { "Id", "Hash", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
