// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mensagem.proto

package ifpb;

public interface MensagemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Mensagem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string text = 2;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 2;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
