// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mensagem.proto

package ifpb;

public interface ResultadoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Resultado)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string hash = 2;</code>
   */
  java.lang.String getHash();
  /**
   * <code>string hash = 2;</code>
   */
  com.google.protobuf.ByteString
      getHashBytes();
}
