// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceIF.proto

package ifpb;

public final class ServiceIF {
  private ServiceIF() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ServiceIF.proto\032\016mensagem.proto21\n\016Env" +
      "iarMensagem\022\037\n\006enviar\022\t.Mensagem\032\n.Resul" +
      "tado23\n\017ReceberMensagem\022 \n\007receber\022\t.Men" +
      "sagem\032\n.Resultado20\n\016ExibirMensagem\022\036\n\005p" +
      "rint\022\t.Mensagem\032\n.ResultadoB\010\n\004ifpbP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ifpb.MensagemOuterClass.getDescriptor(),
        });
    ifpb.MensagemOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
